### PR TITLE
IPv6 compatibility fix submitted by Hugo Landau.

### PR DESCRIPTION
**Pull request by yookoala**
* applied the latest [flup-py3.0 ipv6 patch](https://hg.saddi.com/flup-py3.0/rev/e354ee0f04f8)

### CODE REVIEW

**Comment by pquentin** [comment]
I no longer use flup since I switched to WSGI long ago. I've added you as a collaborator, feel free to consider that this repository is yours.

**Comment by pquentin** [comment]
Maybe it would be best to try to merge the Python 3 patch into upstream?

**Comment by yookoala** [comment]
Thanks.

I agree it would be best to patch upstream.
But I'm not familiar with the Python ecosystem.

What exactly should I do to get the patch upstream?

**Comment by pquentin** [comment]
If my patch had not been applied, the best way would have been to send a patch by email to Allan Saddi <allan@saddi.com>. I'm not sure how to do that with mercurial, since I'm more familiar with git.

I see that my patch was applied: https://hg.saddi.com/flup-py3.0/rev/916cde7b7d57. Maybe you should send an email to ask for a new PyPI release to fix #1?

**Comment by yookoala** [comment]
I have sent an email to @asaddi (allan@saddi.com) about 1 year ago (January, 2017) and got no reply :-(

**Comment by asaddi** [comment]
The [flup-py3 package](https://pypi.python.org/pypi/flup-py3/) on PyPI isn't owned by me.

**Comment by pquentin** [comment]
@asaddi You probably did not uploaded it, but the author (@ashemedai?) marked you as an owner on PyPI. It's bit sad, because the packages that we would want to see are here, but marked as dev: https://pypi.python.org/pypi/flup.

**Comment by asaddi** [comment]
That one I do control. I've gone ahead and uploaded `1.0.3` (same as `1.0.3.dev20161029`).

I was always hesitant to do that since the last released version was py2. But I don't think it matters anymore...

**Comment by pquentin** [comment]
@asaddi Sorry for the confusion! If flup-py3 does not work with Python 2, maybe it's best not to overwrite flup? Thanks for your answers here in any case.

**Comment by pquentin** [comment]
@agushuley Are you the owner of the flup-py3 package on PyPI? Maybe you could update it? Thanks!

**Comment by agushuley** [comment]
@pquentin I can transfer ownership of PyPI package to you, or someone else.

**Comment by pquentin** [comment]
@asaddi Would you like to own flup-py3? Thanks.

**Comment by asaddi** [comment]
I guess so. @agushuley Please transfer ownership to me (or add me as another owner).

I'll go ahead and hide `1.0.3` on `flup` and then eventually upload it to `flup-py3`.

**Comment by agushuley** [comment]
@asaddi, granted to you owner rights

**Pull request merged**
